src/Mews/Captcha/CaptchaServiceProvider.php
Fix https://github.com/mewebstudio/captcha/issues/27
=> Fix can't translate validation message

src/Captcha.php
@mewebstudio requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/mewebstudio/captcha/
=> Scrutinizer Auto-Fixes

composer.json
=> update intervention image version composer.json

src/CaptchaController.php, src/CaptchaServiceProvider.php
=> use route to Controller method for CAPTCHA

src/CaptchaServiceProvider.php, src/LumenCaptchaController.php
=> add support lumen

README.md, src/CaptchaServiceProvider.php
=> add web middleware to captcha route when using Laravel 5.2.x

src/Captcha.php
some tiems the first char can out of the image width.
=> add text left padding

src/CaptchaController.php
=>  Empty the buffer before get capcha

src/CaptchaController.php
=> clear buff if exist

config/captcha.php, src/Captcha.php
Make sure your TTF font supports the correct language.
=> Multibyte string support by pre-splitted characters string

config/captcha.php, src/Captcha.php
Reverts mewebstudio/captcha#146
Incorrect!
=> Revert "Multibyte string support by pre-splitted characters string"

src/Captcha.php
First time input error the session has been removed, but I think the session should be remove when input success.
=> optimize the time to remove the session

README.md, config/captcha.php, src/Captcha.php
Set `math` to `true` in config file to enable Math captcha.
It simply displays two number and ask user for their summation.
Also I've synced this fork with upstream/master, so you'll have no problem in merging.
=> Math Captcha

src/Captcha.php
Thanks @mwllgr
https://github.com/mewebstudio/captcha/pull/170#issue-314535737
=> Method parameters hot fix.

composer.json, src/CaptchaServiceProvider.php, src/Facades/Captcha.php
=> Support for Laravel 7

README.md
I needed this package to use it in an API. at first, I thought it's unusable in my case but after some code review, I've found it's just lack of proper documentation. so I tried to explain it at the Read me file.
don't hesitate to wholly change my comments. just explain it in your way, please!
=> more comments about stateless mode

README.md, config/captcha.php, src/Captcha.php
60 seconds; this should fix #199
=> Add default value for expire & encryption support

README.md
Could you please label the PR as `hacktoberfest-accepted` if you find it satisfactory
=> Added TOC to readme

src/Captcha.php
Setting does not work right now for API captcha requests
=> Add $sensitive check for API captcha

src/Captcha.php
Fixing #220 by makeing the key much shorter
=> Fix too long cache key issue for memcached

composer.json
=> Add Laravel 9.x support

README.md
I have added an example for implementation in Laravel 11
=> Fix : Add detailed examples for laravel 11 in Readme.md

README.md, composer.json, src/Captcha.php
update to intervention/image v3 from intervention/image v2
=> update to intervention/image v3

src/CaptchaServiceProvider.php
#293 it's should fixes problem occurs
=> Update Providers for Intervention Images v3

src/Captcha.php
=> fix: lineWidth & lineColor
